# Generated by Django 4.2.2 on 2023-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidemountapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.CharField(default='No requirements', max_length=350),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
