# Generated by Django 4.2.2 on 2023-06-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidemountapi', '0002_event_requirements_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidemountuser',
            name='profile_image_url',
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events_attending', through='sidemountapi.Attendee', to='sidemountapi.sidemountuser'),
        ),
    ]
